### ISSUE TITLE
Uno can't be added to the list

### ISSUE THREAD

**Issue by Gyndemia** [romancmx/switchlist#30]
When I search for Uno, two pictures of uno come up, identical, but when clicked I can't add either to my list

**Comment by Gyndemia** [comment]
EDIT: same thing with Celeste

**Comment by romancmx** [comment]
I figured it out, the issue was in the css layout. it was hiding the + buttons when the search results were just a few items. Changes should now be live (it may require a hard reload if page is cached).

<img width="396" alt="screen shot 2018-07-05 at 9 20 00 pm" src="https://user-images.githubusercontent.com/645310/42359789-227a8764-8099-11e8-9e70-b4d3a93ba633.png">
<img width="1392" alt="screen shot 2018-07-05 at 9 19 48 pm" src="https://user-images.githubusercontent.com/645310/42359790-22905670-8099-11e8-9d93-ed94f728715a.png">
<img width="1392" alt="screen shot 2018-07-05 at 9 19 43 pm" src="https://user-images.githubusercontent.com/645310/42359791-22a634ea-8099-11e8-886d-0336ed401026.png">

**Comment by romancm** [comment]
@allcontributors please add @Gyndemia for bug
